language: java
sudo: false
jdk:
- oraclejdk8
script:
- ./gradlew publishGhPages --stacktrace
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: Al2jCXZoroibub43SdV7uUZgwRazUj0F64WlPIXgqCfcfhuvYA6geivRTxQrqoxdDJajJBi6OO7k4Ci4tInl4Qx7VT1wQbVmnJQto8uK1JoNIQ+Jrd7/qLrysGwpU4SeMb107KFSAIU7Hn+a/BD5E5Tyajc2JbXpKmFpQVKRaQywecF8yJpKVp2X2zLp3GWm75U2WIlqIgWx++vd5W/ixkK1E+azUYkN5FzV7DdkbKgrn9v4fH+pqh3CL0VAhUUoCOUNHSVE2zRwpazouzMJUKk20pjhnF23eLlkUG+yeOV64RbyXknTjnE8nzRB11A1/D9pMl4dD8BeM5xBZrcZsye4e0FX82XuPbvqkhkF+dvWlUvcJzWtHWm9lvx6P6ZSBC/nuz5/upAqhimP230majIwtie06lrH4KA3g+ilhkYBeTHm/5b4PMaKjVy4e1l6kl67sIF2ot+M52MF68fBPZyz37pFOy6sb88mdl+qrsa+A+VmKt+SphSDqeq8SXXY8QSouQ0dFyjaxGzSPikkiqyl2H9mvmc1Rfc89fwksoBvABcU30l6n3yMFPrcactFYtznralIYukD7gaJB6YvActTa2aBOwv4toFHyGda7PGhsar7ZY7PpovyFCD1sn/gNwGfZOLaDgUDu2qqCMoVlZ6UXNgQmonO4ar0T/GIYos=
